{
 "title": "Verwerkingen",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Munera (Mijn Gemeente)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "target": "SELECT trace_id AS \"Trace ID\", operation_id AS \"Operation ID\", parent_operation_id AS \"Parent operation ID\", name AS \"Operation name\", start_time AS \"Start time\", end_time AS \"End time\", status_code AS \"Status code\", resource_name AS \"Resource name\", resource_version AS \"Resource version\"\nFROM processing_operations\nWHERE start_time > $__timeFrom AND start_time < $__timeTo\nALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Currus (Parkeervergunningsoftware)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "queryText": "SELECT\n  trace_id AS \"Trace ID\", operation_id AS \"Operation ID\", parent_operation_id AS \"Parent operation ID\",\n  name AS \"Operation name\", start_time AS \"Start time\", end_time AS \"End time\", status_code AS \"Status code\",\n  foreign_trace_id AS \"Foreign trace ID\", foreign_operation_id AS \"Foreign operation ID\",\n  resource_name AS \"Resource name\", resource_version AS \"Resource version\"\nFROM processing_operations \nWHERE start_time > \"${__from:date:iso}\" AND start_time < \"${__to:date:iso}\"\nORDER BY start_time DESC",
     "rawQueryText": "SELECT\n  trace_id AS \"Trace ID\", operation_id AS \"Operation ID\", parent_operation_id AS \"Parent operation ID\",\n  name AS \"Operation name\", start_time AS \"Start time\", end_time AS \"End time\", status_code AS \"Status code\",\n  foreign_trace_id AS \"Foreign trace ID\", foreign_operation_id AS \"Foreign operation ID\",\n  resource_name AS \"Resource name\", resource_version AS \"Resource version\"\nFROM processing_operations \nWHERE start_time > \"${__from:date:iso}\" AND start_time < \"${__to:date:iso}\"\nORDER BY start_time DESC",
     "timeColumns": [
      "start_time",
      "end_time"
     ]
    },
    {
     "queryText": "SELECT\n  a.operation_id AS \"Operation ID\", key AS \"Attribute key\", value AS \"Attribute value\"\nFROM processing_operation_attributes a\nINNER JOIN processing_operations o ON o.trace_id = a.trace_id AND o.operation_id = a.operation_id\nWHERE o.start_time > \"${__from:date:iso}\" AND o.start_time < \"${__to:date:iso}\"",
     "rawQueryText": "SELECT\n  a.operation_id AS \"Operation ID\", key AS \"Attribute key\", value AS \"Attribute value\"\nFROM processing_operation_attributes a\nINNER JOIN processing_operations o ON o.trace_id = a.trace_id AND o.operation_id = a.operation_id\nWHERE o.start_time > \"${__from:date:iso}\" AND o.start_time < \"${__to:date:iso}\""
    }
   ]
  },
  {
   "title": "Lamina (RDW)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "queryText": "SELECT\n  trace_id AS \"Trace ID\", operation_id AS \"Operation ID\", parent_operation_id AS \"Parent operation ID\",\n  name AS \"Operation name\", start_time AS \"Start time\", end_time AS \"End time\", status_code AS \"Status code\",\n  foreign_trace_id AS \"Foreign trace ID\", foreign_operation_id AS \"Foreign operation ID\",\n  resource_name AS \"Resource name\", resource_version AS \"Resource version\"\nFROM processing_operations \nWHERE start_time >= \"${__from:date:iso}\" AND start_time < \"${__to:date:iso}\"\nORDER BY start_time DESC",
     "rawQueryText": "SELECT\n  trace_id AS \"Trace ID\", operation_id AS \"Operation ID\", parent_operation_id AS \"Parent operation ID\",\n  name AS \"Operation name\", start_time AS \"Start time\", end_time AS \"End time\", status_code AS \"Status code\",\n  foreign_trace_id AS \"Foreign trace ID\", foreign_operation_id AS \"Foreign operation ID\",\n  resource_name AS \"Resource name\", resource_version AS \"Resource version\"\nFROM processing_operations \nWHERE start_time >= \"${__from:date:iso}\" AND start_time < \"${__to:date:iso}\"\nORDER BY start_time DESC",
     "timeColumns": [
      "start_time",
      "end_time"
     ]
    },
    {
     "queryText": "SELECT\n  a.operation_id AS \"Operation ID\", key AS \"Attribute key\", value AS \"Attribute value\"\nFROM processing_operation_attributes a\nINNER JOIN processing_operations o ON o.trace_id = a.trace_id AND o.operation_id = a.operation_id\nWHERE o.start_time > \"${__from:date:iso}\" AND o.start_time < \"${__to:date:iso}\"",
     "rawQueryText": "SELECT\n  a.operation_id AS \"Operation ID\", key AS \"Attribute key\", value AS \"Attribute value\"\nFROM processing_operation_attributes a\nINNER JOIN processing_operations o ON o.trace_id = a.trace_id AND o.operation_id = a.operation_id\nWHERE o.start_time > \"${__from:date:iso}\" AND o.start_time < \"${__to:date:iso}\""
    }
   ]
  }
 ]
}